name: daytok
description: ""
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  tiktoklikescroller: ^0.2.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  bloc: ^9.0.0
  flutter_bloc: ^9.0.0
  share_plus: ^10.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
